### PR TITLE
improve wildcard expansion for exported nested wildcard

### PR DESCRIPTION
**Pull request by iambumblehead**
wildcard expansion is improved with this PR to resolve https://github.com/iambumblehead/esmock/issues/293

### CODE REVIEW

**Comment by iambumblehead** [comment]
@Jeff-Tham feel free to give any comments or suggestions

This PR improves slightly fragile wildcard improvements added a few weeks back https://github.com/iambumblehead/resolvewithplus/pull/65

**Comment by iambumblehead** [comment]
imho the changes here are pretty good and the updated version is better and more easily understood than previous version.

**Comment by Jeff-Tham** [comment]
Looks good based on the unit test.

**Comment by iambumblehead** [comment]
thanks. a few unit-tests are added... getting ready to publish this and then esmock

**Pull request merged**
